# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashcards.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Flash(object):
    def setupUi(self, Flash):
        Flash.setObjectName(_fromUtf8("Flash"))
        Flash.resize(600, 400)
        Flash.setMinimumSize(QtCore.QSize(0, 0))
        Flash.setMaximumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setPointSize(50)
        Flash.setFont(font)
        Flash.setStyleSheet(_fromUtf8("background-color: rgb(255, 102, 102)"))
        self.centralwidget = QtGui.QWidget(Flash)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 350))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.stackedWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.loadPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPage.sizePolicy().hasHeightForWidth())
        self.loadPage.setSizePolicy(sizePolicy)
        self.loadPage.setObjectName(_fromUtf8("loadPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.loadPage)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mainVLayout = QtGui.QVBoxLayout()
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName(_fromUtf8("mainVLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem)
        self.titleLabel = QtGui.QLabel(self.loadPage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(30)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet(_fromUtf8("color: rgb(255, 102, 102)"))
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.mainVLayout.addWidget(self.titleLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem1)
        self.horizontalFrame = QtGui.QFrame(self.loadPage)
        self.horizontalFrame.setStyleSheet(_fromUtf8(""))
        self.horizontalFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.horizontalFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.loadHLayout = QtGui.QHBoxLayout(self.horizontalFrame)
        self.loadHLayout.setObjectName(_fromUtf8("loadHLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loadHLayout.addItem(spacerItem2)
        self.verticalFrame = QtGui.QFrame(self.horizontalFrame)
        self.verticalFrame.setFrameShape(QtGui.QFrame.Box)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.importVLayout = QtGui.QVBoxLayout(self.verticalFrame)
        self.importVLayout.setObjectName(_fromUtf8("importVLayout"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.importVLayout.addItem(spacerItem3)
        self.importLabel = QtGui.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(20)
        self.importLabel.setFont(font)
        self.importLabel.setStyleSheet(_fromUtf8("color: rgb(255, 102, 102);"))
        self.importLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.importLabel.setObjectName(_fromUtf8("importLabel"))
        self.importVLayout.addWidget(self.importLabel)
        self.importButton = QtGui.QPushButton(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(17)
        self.importButton.setFont(font)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.importVLayout.addWidget(self.importButton)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.importVLayout.addItem(spacerItem4)
        self.loadHLayout.addWidget(self.verticalFrame)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loadHLayout.addItem(spacerItem5)
        self.verticalFrame_2 = QtGui.QFrame(self.horizontalFrame)
        self.verticalFrame_2.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.verticalFrame_2.setFrameShape(QtGui.QFrame.Box)
        self.verticalFrame_2.setObjectName(_fromUtf8("verticalFrame_2"))
        self.loadVLayout = QtGui.QVBoxLayout(self.verticalFrame_2)
        self.loadVLayout.setObjectName(_fromUtf8("loadVLayout"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.loadVLayout.addItem(spacerItem6)
        self.loadedLabel = QtGui.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(20)
        self.loadedLabel.setFont(font)
        self.loadedLabel.setStyleSheet(_fromUtf8("color: rgb(255, 102, 102);"))
        self.loadedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadedLabel.setObjectName(_fromUtf8("loadedLabel"))
        self.loadVLayout.addWidget(self.loadedLabel)
        self.loadedDecks = QtGui.QComboBox(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(18)
        self.loadedDecks.setFont(font)
        self.loadedDecks.setStyleSheet(_fromUtf8(""))
        self.loadedDecks.setObjectName(_fromUtf8("loadedDecks"))
        self.loadVLayout.addWidget(self.loadedDecks)
        self.loadButton = QtGui.QPushButton(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(17)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.loadVLayout.addWidget(self.loadButton)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.loadVLayout.addItem(spacerItem7)
        self.loadedDecks.raise_()
        self.loadedLabel.raise_()
        self.loadButton.raise_()
        self.loadHLayout.addWidget(self.verticalFrame_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loadHLayout.addItem(spacerItem8)
        self.stagedDeck = QtGui.QListView(self.horizontalFrame)
        self.stagedDeck.setEnabled(True)
        self.stagedDeck.setMaximumSize(QtCore.QSize(150, 16777215))
        self.stagedDeck.setObjectName(_fromUtf8("stagedDeck"))
        self.loadHLayout.addWidget(self.stagedDeck)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loadHLayout.addItem(spacerItem9)
        self.mainVLayout.addWidget(self.horizontalFrame)
        self.frame = QtGui.QFrame(self.loadPage)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.mainVLayout.addWidget(self.frame)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.startButton = QtGui.QPushButton(self.loadPage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(20)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_2.addWidget(self.startButton)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.mainVLayout.addLayout(self.horizontalLayout_2)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.mainVLayout)
        self.stackedWidget.addWidget(self.loadPage)
        self.cardPage = QtGui.QWidget()
        self.cardPage.setObjectName(_fromUtf8("cardPage"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.cardPage)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.stackedWidget_2 = QtGui.QStackedWidget(self.cardPage)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(500, 300))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(500, 300))
        self.stackedWidget_2.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.front = QtGui.QWidget()
        self.front.setObjectName(_fromUtf8("front"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.front)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.wordLabel = QtGui.QLabel(self.front)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(40)
        self.wordLabel.setFont(font)
        self.wordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel.setObjectName(_fromUtf8("wordLabel"))
        self.verticalLayout.addWidget(self.wordLabel)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.flipButton = QtGui.QPushButton(self.front)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(18)
        self.flipButton.setFont(font)
        self.flipButton.setObjectName(_fromUtf8("flipButton"))
        self.horizontalLayout_4.addWidget(self.flipButton)
        spacerItem18 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.stackedWidget_2.addWidget(self.front)
        self.back = QtGui.QWidget()
        self.back.setObjectName(_fromUtf8("back"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.back)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.defLabel = QtGui.QLabel(self.back)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(30)
        self.defLabel.setFont(font)
        self.defLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.defLabel.setObjectName(_fromUtf8("defLabel"))
        self.horizontalLayout_6.addWidget(self.defLabel)
        self.stackedWidget_2.addWidget(self.back)
        self.verticalLayout_5.addWidget(self.stackedWidget_2)
        self.progressBar = QtGui.QProgressBar(self.cardPage)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_5.addWidget(self.progressBar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.stackedWidget.addWidget(self.cardPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        Flash.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Flash)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        Flash.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Flash)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Flash.setStatusBar(self.statusbar)
        self.actionFile = QtGui.QAction(Flash)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionLoad_Deck = QtGui.QAction(Flash)
        self.actionLoad_Deck.setObjectName(_fromUtf8("actionLoad_Deck"))
        self.actionQuit = QtGui.QAction(Flash)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionImport_from_Text = QtGui.QAction(Flash)
        self.actionImport_from_Text.setObjectName(_fromUtf8("actionImport_from_Text"))
        self.actionLoad_Deck_2 = QtGui.QAction(Flash)
        self.actionLoad_Deck_2.setObjectName(_fromUtf8("actionLoad_Deck_2"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Flash)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Flash)

    def retranslateUi(self, Flash):
        Flash.setWindowTitle(_translate("Flash", "MainWindow", None))
        self.titleLabel.setText(_translate("Flash", "Flashcard Manager", None))
        self.importLabel.setText(_translate("Flash", "Import Deck", None))
        self.importButton.setText(_translate("Flash", "Search", None))
        self.loadedLabel.setText(_translate("Flash", "Decks Found", None))
        self.loadButton.setText(_translate("Flash", "Load ->", None))
        self.startButton.setText(_translate("Flash", "Test Me!", None))
        self.wordLabel.setText(_translate("Flash", "Flashcard Front", None))
        self.flipButton.setText(_translate("Flash", "Flip", None))
        self.defLabel.setText(_translate("Flash", "Flashcard Back", None))
        self.menuFile.setTitle(_translate("Flash", "File", None))
        self.actionFile.setText(_translate("Flash", "File", None))
        self.actionLoad_Deck.setText(_translate("Flash", "Load Deck", None))
        self.actionQuit.setText(_translate("Flash", "Quit", None))
        self.actionImport_from_Text.setText(_translate("Flash", "Import from Text", None))
        self.actionLoad_Deck_2.setText(_translate("Flash", "Load Deck", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Flash = QtGui.QMainWindow()
    ui = Ui_Flash()
    ui.setupUi(Flash)
    Flash.show()
    sys.exit(app.exec_())

