#!/bin/bash
# package python program to .app

pyexpath="$(which python)"

if [ $pyexpath != "/Users/jonahmajumder/.conda/envs/qtenv/bin/python" ]; then
	echo "Wrong anaconda environment (correct environment is 'qtenv').";
	exit 1;
fi

echo "Running script to package Flash app..."

if [ -f setup.py ]; then
	rm setup.py;
fi

py2applet --make-setup --packages=PyQt5 Flash.py *.ui FlashIcon.icns

rm -rf build dist

# if the below fails due to some macholib-libpython dylib:
# ln -s existing_lib lib_script_can't find (a symbolic link)

python setup.py py2app

cp *.ui ./dist/Flash.app/Contents/MacOS/

echo "Running application from terminal..."

./dist/Flash.app/Contents/MacOS/Flash